'use strict';

/**
 * @ngdoc function
 * @name matchUpApp.controller:SportsCtrl
 * @description
 * # SportsCtrl
 * Controller of the matchUpApp
 */
angular.module('matchUpApp')
  .controller('SportsCtrl', ["$scope", "$rootScope", function ($scope, $rootScope) {
    $scope.sportsList = ["Aerobatics",
"Air racing",
"Hot air ballooning|Ballooning",
"Cluster ballooning",
"Hopper ballooning",
"Gliding",
"Hang gliding",
"Powered hang glider",
"Human powered aircraft",
"Model aircraft",
"Parachuting",
"Banzai skydiving",
"BASE jumping",
"Skydiving",
"Skysurfing",
"Wingsuit flying",
"Paragliding",
"Powered paragliding",
"Paramotoring",
"Ultralight aviation",
 "Field archery",
 "Flight archery",
 "Gungdo",
 "Indoor archery",
 "Kyūdō",
 "Popinjay (sport)|Popinjay",
 "Target archery",
 "Ball badminton",
 "Biribol",
 "Goalroball",
 "Bossaball",
 "Fistball",
 "Footbag net",
 "Football tennis",
 "Footvolley",
 "Hooverball",
 "Peteca",
 "Pickleball",
 "Sepak takraw",
 "Sipa",
 "Throwball",
 "Volleyball",
 "Beach volleyball",
"Water Volleyball",
 "Paralympic volleyball",
 "Wallyball",
 "Tennis",
 "Basketball",
 "Beach basketball",
 "Deaf basketball",
 "3x3 (basketball)|3x3",
 "Streetball",
 "Water basketball",
 "Wheelchair basketball",
 "Korfball",
 "Netball",
 "Fastnet (netball)|Fastnet",
 "Indoor netball",
 "Slamball",
"Baseball",
"Softball",
"Slow Pitch",
"Bat-and-Trap",
"British baseball", 
"Brännboll",
"Corkball", 
"Cricket",
 "Indoor cricket (UK variant)|Indoor cricket",
 "Limited overs cricket",
 "One Day International", 
 "Test cricket",      
 "Twenty20",  
 "Danish longball",
 "Kickball",
"Lapta (game)|Lapta", 
"The Massachusetts Game",
"Matball",
"Oina", 
"Old Cat",
"Over-the-line",  
"Palant",
"Pesäpallo",
"Punchball",
"Rounders",
"Scrub baseball",
"Stickball",
"Stool ball",
"Tee Ball|T-Ball",
"Town ball",
"Vigoro",
"Wireball",
"Wiffleball",
 "Baton twirling",
 "Skateboarding",
 "Freestyle scootering|Scootering",
 "Casterboarding",
 "Freeboard (skateboard)",
 "Longboarding",
 "Streetboarding",
 "Skysurfing",
 "Streetluge",
 "Snowboarding",
 "Mountainboarding",
 "Sandboarding",
 "Snowkiting",
 "Surfing",
 "Swing boarding",
"Wakesurfing",
 "Bodyboarding",
 "Riverboarding",
 "Skimboarding",
 "Windsurfing",
 "Wakeboarding",
 "Kneeboarding",
"Pennyboarding",
 "Curving",
 "Dodgeball",
 "Ga-ga",
 "Keep Away",
 "Kin-Ball",
 "Prisoner Ball",
 "muggle quidditch|Quidditch",
 "Rundown",
 "Yukigassen",
 "Handball",
 "Rock Climbing",
 "Bouldering",
 "Deep-water soloing",
 "Sport climbing",
 "Traditional climbing",
 "Aid Climbing",
 "Ice Climbing",
 "Mixed climbing",
 "Abseiling",
 "Mountaineering",
 "Canyoning",
 "Hiking",
 "Rope climbing|Rope Climbing",
 "Pole climbing (gymnastic)|Pole climbing",
 "Coasteering",
 "Artistic cycling",
 "Bicycle Motocross",
 "BMX",
 "Cyclo-cross",
 "Cross-country mountain biking",
 "Cycle polo",
 "Cycle speedway",
 "Downhill mountain biking",
 "Dirt jumping",
 "Freestyle BMX",
 "Hardcourt Bike Polo",
 "Road bicycle racing",
 "Track cycling",
 "Underwater cycling",
 "Skibobbing",
 "Unicycling",
 "Mountain unicycling",
 "Unicycle trials",
 "Unicycle hockey",
 "Unicycle basketball",
 "Daitō-ryū Aiki-jūjutsu|Aiki-jūjutsu",
 "Aikido",
"Hala (sport)|Hala",
 "Kinomichi",
 "Jujutsu",
 "Judo",
 "Brazilian Jiu-Jitsu",
 "Sambo (martial art)",
 "Sumo",
 "Wrestling",
"Amateur wrestling",
"Greco-Roman wrestling",
"Freestyle wrestling",
 "Folk wrestling",
 "Boli Khela",
 "Dumog",
 "Glima",
 "Kurash",
 "Lancashire wrestling",
 "Catch wrestling",
 "Malla-yuddha",
 "Mongolian wrestling",
 "Pehlwani",
"Professional wrestling",
 "Schwingen",
 "Shuai Jiao",
 "Ssireum",
 "Varzesh-e Pahlavani",
 "Yağlı Güreş",
 "Greek wrestling",
 "Choi Kwang-Do",
 "Cockfighting",
 "Boxing",
 "Bokator",
 "Capoeira",
 "Fujian White Crane",
 "Karate",
 "Kenpō",
 "Kickboxing",
 "Lethwei",
 "Muay Thai",
 "Pradal Serey",
 "San shou",
 "Savate",
 "Shaolin kung fu",
 "Sikaran",
 "Silat",
 "Subak",
 "Taekkyeon",
 "Taekwondo",
 "Taido",
 "Tang Soo Do",
 "Wing Chun",
 "Wing Tsun",
 "Zui Quan",
 "Amateur pankration",
 "Baguazhang",
 "Bando",
 "Bartitsu",
 "Bujinkan",
 "Hapkido",
 "Hwa Rang Do",
 "Jeet Kune Do",
 "Kajukenbo",
 "Kalarippayattu",
 "Krav Maga",
 "Kuk Sool Won",
 "MCMAP",
 "Mixed martial arts",
 "Northern Praying Mantis",
 "Ninjutsu",
 "Pankration",
 "Pencak Silat",
 "Sanshou",
 "Shidōkan Karate",
 "Shōrin-ryū Shidōkan",
 "Shoot boxing",
 "Shootfighting",
 "Shorinji Kempo",
 "Systema",
 "T'ai chi ch'uan",
 "Vajra-mushti",
 "Vale tudo",
 "Vovinam",
 "Xingyiquan",
 "Axe throwing",
 "Battōjutsu",
 "Battle gaming|Boffer Fighting",
 "Eskrima",
 "Egyptian stick fencing",
 "Fencing",
 "Gatka",
 "Hojōjutsu",
 "Iaidō",
 "Iaijutsu",
 "Jōdō",
 "Jogo do Pau",
 "Jūkendō",
 "Juttejutsu",
 "Kendo",
 "Kenjutsu",
 "kung fu",
 "Kyūdō",
 "Kyūjutsu",
 "Modern Arnis",
 "Naginatajutsu",
 "Nguni stick-fighting",
 "Okinawan kobudō",
 "Shurikenjutsu",
 "Silambam",
 "Sōjutsu",
 "Swordfighting",
 "wushu (sport)",
 "gumdo",
 "Wing Tsun",
 "Airsoft",
 "Laser tag",
 "Paintball",
 "Carom billiards",
 "Three-cushion",
 "Five-pins",
 "Balkline and straight rail",
 "Cushion caroms",
 "Four-ball billiards|Four-ball",
 "Artistic billiards",
 "Novuss",
 "Pocket billiards",
 "Eight-ball",
"Blackball (pool)|Blackball",
 "Nine-ball",
 "Straight pool",
 "One-pocket",
 "Three-ball",
 "Seven-ball",
 "Ten-ball",
 "Rotation (pool)|Rotation",
 "Baseball pocket billiards",
 "Cribbage (pool)",
 "Bank pool",
 "Artistic pool",
 "Trick shot",
 "Speed pool",
 "Bowlliards",
 "Chicago (pool)|Chicago",
 "Kelly pool",
 "Cutthroat (pool)|Cutthroat",
 "Killer (pool)|Killer",
 "Russian pyramid",
 "Snooker",
 "American snooker",
 "Sinuca brasileira",
 "Six-red snooker",
 "Snooker plus",
 "English billiards",
 "Bottle pool",
 "Cowboy (billiards)|Cowboy",
 "Bagatelle",
 "Bar billiards",
 "Bumper pool",
 "Buzkashi",
 "Barrel Racing",
 "Campdrafting",
 "Charreada",
 "Chilean rodeo",
 "Cross-country equestrianism|Cross Country",
 "Dressage",
 "Endurance riding",
 "English Pleasure",
 "Equitation",
 "Eventing",
 "Equestrian vaulting",
 "Gymkhana",
 "Harness racing",
 "Horse racing",
 "Horseball",
 "Hunter",
 "Hunter-jumpers",
 "Jousting",
 "Polo",
 "Pato",
 "Reining",
 "Rodeo",
 "Show Jumping",
 "Steeplechase (horse racing)|Steeplechase",
 "Team penning",
 "Tent pegging",
 "Western Pleasure",
 "Polocrosse",
 "Angling",
 "Big-game fishing",
 "Casting (fishing)|Casting",
 "Noodling",
 "Spearfishing",
 "Sport fishing",
 "Surf fishing",
 "Rock fishing",
 "Fly Fishing",
 "Ice Fishing",
 "Beach Ultimate",
 "Disc dog",
 "Disc golf",
 "Flying disc games#Urban disc golf|Disc golf (urban)",
 "Dodge disc",
 "Double disc court",
 "Flutterguts",
 "Flying disc freestyle|Freestyle",
 "Flying disc games#Freestyle competition|Freestyle competition",
 "Fricket",
 "Goaltimate",
 "Guts (game)",
 "Hot box (game)|Hot box",
 "Ringo (sport)|Ringo",
 "Chinlone",
 "Cuju",
 "Episkyros",
 "Harpastum",
 "Kemari",
 "Ki-o-rahi",
 "Marn Grook",
 "Woggabaliri",
 "Yubi lakpi",
 "Medieval football",
 "Ba game",
 "Caid (sport)|Caid",
 "Calcio Fiorentino",
 "Camping (game)",
 "Chester-le-Street",
 "Cnapan",
 "Cornish hurling",
 "Haxey Hood",
 "Knattleikr",
 "La soule",
 "Lelo burti",
 "Mob football",
 "Royal Shrovetide Football",
 "Uppies and Downies",
 "Association football",
 "Jorkyball",
 "Paralympic association football|Paralympic football",
 "Powerchair Football",
 "Five-a-side football",
 "Beach soccer",
 "Futebol de Salão",
 "Futsal",
 "Papi fut",
 "Indoor soccer",
 "Masters Football",
 "Street football",
 "Freestyle football",
 "Keepie uppie",
 "Swamp football",
 "Three sided football",
 "Australian football",
 "Nine-a-side footy",
 "Rec footy",
 "Metro footy",
 "English public school football games|English school games",
 "Eton field game|Field game",
 "Eton wall game|Wall game",
 "Harrow Football",
 "Gaelic football",
"Ladies' Gaelic football",
 "Gridiron football",
 "American football",
 "Eight-man football",
 "Flag football",
 "Indoor American football|Indoor football",
 "Arena football",
 "Nine-man football",
 "Six-man football",
 "Sprint football",
 "Touch football (American)|Touch football",
 "Canadian football",
 "Street football (American)",
 "Rugby football",
 "Beach rugby",
 "Rugby league",
 "Masters Rugby League",
 "Mini footy",
 "Mod league",
 "Rugby league nines",
 "Rugby league sevens",
 "Tag Rugby",
 "Touch football (rugby league)|Touch Football",
 "Wheelchair rugby league",
 "Rugby union",
 "American flag rugby",
 "Mini rugby",
 "Rugby sevens",
 "Tag Rugby",
 "Touch rugby",
 "Rugby tens",
 "Snow rugby",
"Snail racing",
 "Austus",
 "Football tennis",
 "Footvolley",
 "International rules football",
 "Kickball",
 "Kronum",
 "Matball",
 "Samoa Rules",
 "Speedball (American ball game)|Speedball",
 "Swedish football (code)|Swedish football",
 "Universal football",
 "Volata",
 "Match play",
 "Skins game",
 "Stroke play",
 "Shotgun start",
 "Speed golf",
 "Miniature golf",
 "Artistic gymnastics",
 "Balance beam (gymnastics)|Balance Beam",
 "Floor (gymnastics)|Floor",
 "Horizontal bar|High Bar",
 "Parallel Bars",
 "Pommel Horse",
 "Rings (gymnastics)|Still Rings",
 "Uneven Bars",
 "Vault (gymnastics)|Vault",
 "Toss juggling|Juggling",
 "Rhythmic gymnastics",
"Ball (rhythmic gymnastics)|Ball",
"Juggling club|Club",
"Hoop (rhythmic gymnastics)|Hoop",
"Ribbon (rhythmic gymnastics)|Ribbon",
"Rope (rhythmic gymnastics)|Rope",
 "Jump rope#Competition|Rope jumping",
 "Sports acrobatics",
 "Sports aerobics",
 "Slacklining",
 "Trampolining",
 "Trapeze",
 "Flying trapeze",
 "Static trapeze",
 "Gaelic Handball",
 "Goalball",
 "Tchoukball",
 "Team handball",
 "Beach handball",
 "Czech handball",
 "Field handball",
 "Ringball",
 "Torball",
 "Volata",
 "Water polo",
 "Beagling",
 "Trophy hunting|Big game hunting",
 "Deer hunting",
 "Fox hunting",
 "Hare coursing",
 "Wolf hunting",
 "Bandy",
 "Rink bandy",
 "Broomball",
 "Curling",
 "Ice hockey",
 "Ringette",
 "Ice yachting",
 "Figure skating",
 "Kite buggy",
 "Kite fighting",
 "Kite landboarding",
 "Kitesurfing",
 "Parasailing",
 "Snow kiting",
 "Sport kite",
 "Adventure racing",
 "Biathlon",
 "Duathlon",
 "Decathlon",
 "Heptathlon",
 "Icosathlon",
 "Modern pentathlon",
 "Pentathlon",
 "Triathlon",
 "Woodsman",
 "Geocaching",
 "Orienteering",
 "Rogaining",
 "Letterboxing (hobby)|Letterboxing",
 "Waymarking",
 "American handball",
 "Australian Handball",
 "Basque Pelota",
 "Jai Alai",
 "Fives",
 "Eton Fives",
 "Rugby Fives",
 "Frisian handball",
 "Four square",
 "Gaelic handball",
 "Jeu de paume",
 "Palla",
 "Patball",
 "Valencian pilota",
 "Aerobatics (radio-controlled aircraft)|Model Aerobatics",
 "Radio-controlled car#Hobby radio control|RC Racing",
 "Robot combat",
 "Slot car racing",
 "Endurance",
 "5K run",
 "10K run",
 "Cross-country running",
 "Half marathon",
 "Marathon",
 "Road running",
 "Tower running",
 "Ultramarathon",
 "Sprint (running)|Sprint",
 "Hurdles",
 "Ice yachting",
 "Land sailing",
 "Land windsurfing",
 "Sailing (sport)|Sailing",
 "Windsurfing",
 "Kitesurfing|Kiteboarding",
 "Dinghy sailing",
 "Alpine skiing",
 "Cross-country skiing",
 "Freestyle skiing",
 "Nordic combined",
 "Nordic skiing",
 "Ski jumping",
 "Skijoring",
 "Ski touring",
 "Speed skiing",
 "Telemark skiing",
 "Bobsleigh",
 "Luge",
 "Skibobbing",
 "Skeleton (sport)|Skeleton",
 "Toboggan",
 "Clay pigeon shooting",
 "Skeet shooting",
 "Trap shooting",
 "Sporting clays",
 "Target shooting",
 "Field target",
 "Fullbore target rifle",
 "High Power Rifle",
 "Benchrest shooting",
 "Metallic silhouette",
 "Practical shooting",
 "Cowboy Action Shooting",
 "Metallic silhouette shooting",
 "Sport stacking",
 "Hornussen",
 "Hockey",
 "Ball hockey",
 "Bando (sport)|Bando",
 "Bandy",
 "Rink bandy",
 "Broomball",
 "Moscow broomball",
 "Field Hockey",
 "Indoor field hockey",
 "Floorball",
 "Ice hockey",
 "Pond hockey",
 "Power hockey",
 "Ringette",
 "Ice sledge hockey|Sledge hockey",
 "Underwater ice hockey",
 "Roller hockey",
 "Inline hockey",
 "Roller hockey (Quad)",
 "Skater hockey",
 "Rossall Hockey",
 "Spongee",
 "Street hockey",
 "Underwater hockey",
 "Unicycle hockey",
 "Cammag",
 "Hurling",
 "Camogie",
 "Shinty",
 "Composite rules shinty-hurling",
 "Lacrosse",
 "Box lacrosse",
 "Field lacrosse",
 "Women's lacrosse",
 "Intercrosse",
 "Polo",
 "Bicycle polo",
 "Canoe polo",
 "Cowboy polo",
 "Elephant polo",
 "Horse polo",
 "Segway polo",
 "Yak polo",
 "Polocrosse",
 "Free running",
 "Freestyle Footbag",
 "Freestyle Football",
 "Powerbocking",
 "Parkour",
 "British Bulldogs (game)|British bulldogs",
 "Capture the flag",
 "Hana Ichi Monme",
 "Hide and seek",
 "Jugger",
 "Kabaddi",
 "Kho kho",
 "Kick the can",
 "Oztag",
 "Red rover",
 "Tag (game)|Tag",
 "Hiking",
 "Backpacking (wilderness)",
 "Race Walking",
 "wikt:bushwhacking|Bushwhacking",
 "Walking",
 "American handball",
 "Australian handball",
 "Basque pelota",
 "Butts Up",
 "Chinese handball",
 "Fives",
 "Gaelic handball",
 "International fronton",
 "Jorkyball",
 "Racquetball",
 "Squash (sport)|Squash",
 "Squash tennis",
 "Suicide (game)",
 "Valencian frontó",
 "Wallball",
 "Wallyball",
"Canoeing",
"Outrigger canoeing",
 "Creeking",
 "Flyak",
 "Freeboating",
 "Royak",
 "Sea kayaking",
 "Squirt Boating",
 "Surf Kayaking",
 "Whitewater kayaking",
 "Rafting",
 "Rafting#White water rafts|White water rafting",
 "Rowing (sport)",
 "Gig racing",
 "Coastal and ocean rowing",
 "Surfboat",
 "Single scull",
 "Dragon boat|Dragon boat racing",
 "Water Polo",
 "Canoe Polo",
 "Waboba",
 "Underwater football",
 "Underwater rugby",
 "Underwater hockey",
 "Backstroke",
 "Breaststroke",
 "Butterfly stroke",
 "Freestyle swimming",
 "Individual Medley",
 "Synchronized swimming",
 "Medley swimming|Medley relay",
 "Finswimming#Disciplines and Distances|Bifins (finswimming)",
 "Finswimming#Disciplines and Distances|Surface finswimming",
 "Finswimming#Disciplines and Distances|Apnoea finswimming",
 "Aquathlon (underwater wrestling)",
 "Freediving",
 "Finswimming#Disciplines and Distances|Immersion finswimming",
 "Scuba Diving",
 "Spearfishing",
 "Snorkelling",
 "Sport diving (sport)",
 "Underwater hockey",
 "Underwater orienteering",
 "Underwater photography (sport)",
 "Underwater target shooting",
 "Diving",
 "Basque rural sports|Basque traditional weightlifting",
 "Bodybuilding",
 "Highland Games",
 "Olympic weightlifting",
 "Powerlifting",
 "Strength athletics|Strength athletics (strongman)",
 "Steinstossen",
 "Autocross",
 "Autograss",
 "Banger racing",
 "Board track racing",
 "Demolition derby",
 "Desert racing",
 "Dirt track racing",
 "Drag racing",
 "Drifting (motorsport)|Drifting",
 "Folkrace",
 "Formula racing",
 "Formula Libre",
 "Formula Student",
 "Hillclimbing",
 "Ice racing",
 "Kart racing",
 "Land speed records",
 "Legends car racing",
 "Midget car racing",
 "Monster truck",
 "Mud bogging",
 "Off-road racing",
 "Pickup truck racing",
 "Production car racing",
 "Race of Champions",
 "Rally raid",
 "Rallycross",
 "Rallying",
 "Regularity rally",
 "Road racing",
 "Short track motor racing",
 "Snowmobile#Types of races|Snowmobile racing",
 "Sports car racing",
 "Sprint car racing",
 "Street racing",
 "Stock car racing",
 "Time Attack",
 "Tractor pulling",
 "Touring car racing",
 "Truck racing",
 "Historic motorsport|Vintage racing",
 "Wheelstand competition",
 "Drag boat racing",
 "F1 Powerboat Racing",
 "Hydroplane racing",
 "Jet sprint boat racing",
 "Offshore powerboat racing",
 "Personal water craft",
 "Auto Race (Japanese sport)|Auto Race",
 "Board track racing",
 "Cross-country rally",
 "Endurance racing (motorsport)|Endurance racing",
 "Enduro",
 "Freestyle Motocross",
 "Grand Prix motorcycle racing",
 "Grass Track",
 "Hill Climb",
 "Ice Racing",
 "Ice speedway",
 "Indoor enduro",
 "Motocross",
 "Motorcycle drag racing",
 "Motorcycle speedway",
 "Off-Road",
 "Rally Raid",
 "Road racing",
 "Superbike racing",
 "Supercross",
 "Supermoto",
 "Super sport (motorcycle)|Supersport racing",
 "Superside",
 "Track racing",
 "Trial",
 "Isle of Man TT|TT racing",
 "Freestyle Motocross|Free-style moto",
 "All-terrain vehicle#Sport competition|All-terrain vehicle competition",
"Airsoft",
"Archery",
"Paintball",
 "Stihl Timbersports Series",
 "Quizzing",
 "Speedcubing",
 "Pocket Cube|2x2x2",
 "Rubik's Cube|3x3x3",
 "Rubik's Revenge|4x4x4",
 "5x5x5",
 "V-Cube 6|6x6x6",
 "V-Cube 7|7x7x7",
 "Arimaa",
 "Backgammon",
 "Chess",
 "Chess960",
 "Losing Chess",
 "Checkers",
 "Chinese Checkers",
 "Diplomacy (game)|Diplomacy",
 "Dominoes",
 "Draughts",
 "Go (board game)|Go",
 "Go-Moku",
 "Jacquet (game)|Jacquet",
 "Mancala",
 "Mahjong",
 "Risk (game)|Risk",
 "Scrabble",
 "Shogi",
 "Sholo Guti",
 "Sogo (game)|Sogo",
 "Stratego",
 "Sudoku",
 "Xiangqi",
 "Call of Duty",
 "Counter-Strike",
 "Dota 2",
 "FIFA 15",
 "Halo (series)|Halo",
 "Hearthstone: Heroes of Warcraft",
 "Heroes of the Storm",
 "League of Legends",
 "NBA 2K15",
 "NHL 15",
 "Smite (video game)|Smite",
 "StarCraft II: Heart of the Swarm",
 "World of Tanks",
 "World of Warcraft",
 "Banzai skydiving",
 "Bungee jumping",
 "Hot air ballooning",
  "Steeplechase (athletics)|Steeplechase",
  "cross country running|Cross-Country",
  "Jumping",
 "Triple jump",
 "Long jump",
 "High jump",
 "Pole vault",
 "Axe throwing",
 "Discus throw|Discus",
 "Hammer throw",
 "Javelin throw|Javelin",
 "Atlatl",
 "Shot put",
  "Race Walking",
 "Combat robot",
 "Contesting",
 "Video game|Gaming",
 "Geo caching",
 "Radio control|Radio-control vehicles",
 "Chariot Racing",
 "Cross-country skiing",
 "Running",
 "Rowing (sport)|Rowing",
 "Swimming (sport)|Swimming",
 "Wheelchair racing",
 "Wood chopping",
 "Marching Band",
 "Drum and bugle corps (modern)|Drum Corps",
 "Aggressive inline skating",
 "Artistic roller skating",
 "Figure skating",
 "Freestyle slalom skating",
 "Ice dancing",
 "Ice skating",
 "Inline speed skating",
 "Rinkball",
 "Rink hockey",
 "Roller derby",
 "Roller skating",
 "Short track speed skating",
 "Skater hockey",
 "Speed skating",
 "Synchronized skating",
 "Boardercross",
 "Freestyle snowboarding",
 "Snowboarding",
 "Ski flying",
 "Skibob",
 "Snowshoeing",
 "Skiboarding",
 "Arm Wrestling",
 "Olympic weightlifting",
 "Powerlifting",
 "Strongman (strength athlete)|Strongman",
 "Thumb wrestling",
 "Toe wrestling",
 "Tug-o-war",
 "Wood chopping",
 "Wood splitting",
 "Zourkhaneh",
 "Air hockey",
 "Backgammon",
 "Beer Pong",
 "Connect Four",
 "Cue sports",
 "Draughts",
 "Dominoes",
 "Headis",
 "Janggi",
 "Mahjong",
 "Reversi",
 "Shogi",
 "Scrabble",
 "Subbuteo",
 "Table Football",
 "ITHF table hockey|Table Hockey",
 "Table Tennis",
 "Xiangqi",
 "Archery",
 "Axe throwing",
 "Bocce",
 "Bocce volo",
 "Boccia",
 "Bolas criollas",
 "Boules",
 "Bowling",
 "Bowls",
 "Calva",
 "Cornhole",
 "Croquet",
 "Cue sports",
 "Darts",
 "Golf",
 "Horseshoes",
 "Jeu provençal",
 "Knife throwing",
 "Kubb",
 "Matball",
 "Pall mall (game)|Pall mall",
 "Pétanque",
 "Pitch and putt",
 "Punto, raffa, volo",
 "Shooting sports|Shooting",
 "Shuffleboard",
 "Skittles (sport)|Skittles",
 "Skee ball",
 "Trugo",
 "Woodball",
 "Basketball",
 "Bat-and-ball games|Bat and ball games",
 "Bowling",
 "Basque pelota",
 "Bunnock",
 "Camogie",
 "Football",
 "Gateball",
 "Gaelic Football",
 "team handball|Handball",
 "Hardcourt Bike Polo",
 "Hockey",
 "Horseshoe",
 "Hurling",
 "Kickball",
 "Lacrosse",
 "Mesoamerican ballgame",
 "Muggle Quidditch",
 "Newcomb ball",
 "Polo",
 "Paintball",
 "muggle quidditch|Quidditch",
 "Rowing (sport)|Rowing",
 "Sepak Takraw",
 "Tennis Polo",
 "Ultimate (sport)|Ultimate",
 "Underwater football",
 "Woodsman",
 "Volleyball",
 "Kite flying",
 "parachuting",
 "Hot Air Balloon Racing",
"43-Man Squamish",
"Calvinball",
"Quidditch|Quidditch (Harry Potter)",
 "Chess Boxing",
 "Competitive eating",
 "Egg and spoon race",
 "Extreme ironing",
 "Footbag",
 "Haggis hurling",
 "Lumberjack#Loggersports|Lumberjack sports",
 "Aizkolaritza",
 "Axe throwing",
 "Logrolling (sport)|Logrolling",
 "Wood chopping",
 "Wood splitting",
 "Patball",
 "Ringette",
 "Sack race",
 "Soap shoes",
 "Tennikoit",
 "Tetherball",
 "Three-legged race",
 "Wallball",
"List of types of games",
"Team sport"];
    
    $rootScope.sports = $rootScope.sports || [{
    	name: "",
    	skill: "1"
    }];
    
    $scope.addSport = function(){
      $rootScope.sports = $rootScope.sports || [];
    	$rootScope.sports.push({})
    }
    
  }]);